/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(pages)'}/CaptainLogin` | `/CaptainLogin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(pages)'}/CaptainSignup` | `/CaptainSignup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(pages)'}/Header` | `/Header`; params?: Router.UnknownInputParams; } | { pathname: `${'/(pages)'}/UserLogin` | `/UserLogin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(pages)'}/UserSignup` | `/UserSignup`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(pages)'}/CaptainLogin` | `/CaptainLogin`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(pages)'}/CaptainSignup` | `/CaptainSignup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(pages)'}/Header` | `/Header`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(pages)'}/UserLogin` | `/UserLogin`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(pages)'}/UserSignup` | `/UserSignup`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(pages)'}/CaptainLogin${`?${string}` | `#${string}` | ''}` | `/CaptainLogin${`?${string}` | `#${string}` | ''}` | `${'/(pages)'}/CaptainSignup${`?${string}` | `#${string}` | ''}` | `/CaptainSignup${`?${string}` | `#${string}` | ''}` | `${'/(pages)'}/Header${`?${string}` | `#${string}` | ''}` | `/Header${`?${string}` | `#${string}` | ''}` | `${'/(pages)'}/UserLogin${`?${string}` | `#${string}` | ''}` | `/UserLogin${`?${string}` | `#${string}` | ''}` | `${'/(pages)'}/UserSignup${`?${string}` | `#${string}` | ''}` | `/UserSignup${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(pages)'}/CaptainLogin` | `/CaptainLogin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(pages)'}/CaptainSignup` | `/CaptainSignup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(pages)'}/Header` | `/Header`; params?: Router.UnknownInputParams; } | { pathname: `${'/(pages)'}/UserLogin` | `/UserLogin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(pages)'}/UserSignup` | `/UserSignup`; params?: Router.UnknownInputParams; };
    }
  }
}
